FROM ubuntu:14.04
RUN export DEBIAN_FRONTEND="noninteractive"
RUN apt-get update && \
	apt-get install -qq -y \
		build-essential \
		cmake \
		libboost-all-dev \
		libopencv-dev \
		cimg-dev \
		cimg-doc \
		cimg-examples \
		libpng-dev \
		libpng++-dev \
		git \
	&& apt-get clean \
    && rm -rf /var/lib/apt/lists/*

RUN cd /app && \
	git clone https://github.com/davidstutz/glog && \
	cd glog && \
	git reset --hard 0b0b022 && \
	./configure && \
	make

RUN cd /app/ && \
	git clone https://github.com/davidstutz/superpixel-benchmark.git && \
	git submodule update --init --recursive && \
	mkdir build && \
	cd build && \
	cmake .. -DGLOG_ROOT_DIR=/app/glog && \
	make
